import { Round } from "./types";

export const jasonRecentRounds: Round[] = [
  {
    id: "rnd_001",
    date: "2024-11-13",
    course: "Fox Hollow Golf Course",
    score: 78,
    par: 72,
    differential: "+6",
    holes: [4, 5, 3, 4, 4, 5, 3, 4, 4, 4, 5, 3, 4, 4, 5, 3, 4, 4],
    stats: {
      putts: 32,
      fairways: "9/14",
      greens: "11/18",
      penalties: 2,
      birdies: 3,
      pars: 10,
      bogeys: 4,
      doubleBogeys: 1,
    },
    conditions: "Sunny, 75°F, 8mph wind",
    playingPartners: ["Mike Thompson", "Dave Wilson"],
    notes: "Finally figured out the approach on #7. Driver was money today.",
    images: ["/rounds/fox-hollow-scorecard-11-13.jpg"],
    xpEarned: 85,
    trophyBalls: [],
  },
  {
    id: "rnd_002",
    date: "2024-11-10",
    course: "Black Desert Resort",
    score: 81,
    par: 72,
    differential: "+9",
    holes: [5, 4, 4, 5, 5, 6, 3, 4, 5, 4, 5, 4, 5, 4, 5, 3, 4, 5],
    stats: {
      putts: 34,
      fairways: "7/14",
      greens: "9/18",
      penalties: 3,
      birdies: 1,
      pars: 8,
      bogeys: 6,
      doubleBogeys: 3,
    },
    conditions: "Partly cloudy, 68°F, 15mph wind",
    playingPartners: ["Sarah Chen"],
    notes: "Wind was brutal. Lost 2 balls on #15.",
    xpEarned: 75,
    trophyBalls: ["desert-warrior"],
  },
  {
    id: "rnd_003",
    date: "2024-11-06",
    course: "Sand Hollow Resort",
    score: 77,
    par: 72,
    differential: "+5",
    holes: [4, 4, 3, 4, 3, 5, 4, 5, 4, 4, 5, 3, 4, 4, 5, 4, 4, 4],
    stats: {
      putts: 30,
      fairways: "10/14",
      greens: "12/18",
      penalties: 1,
      birdies: 2,
      pars: 12,
      bogeys: 3,
      doubleBogeys: 1,
    },
    conditions: "Clear, 72°F, 5mph wind",
    playingPartners: ["John Martinez", "Tom Reynolds"],
    notes: "Best putting round in months. Need to work on driving accuracy.",
    xpEarned: 90,
    trophyBalls: [],
  },
  {
    id: "rnd_004",
    date: "2024-11-03",
    course: "Coral Canyon Golf Club",
    score: 82,
    par: 72,
    differential: "+10",
    holes: [5, 5, 4, 4, 4, 6, 3, 5, 4, 4, 5, 4, 5, 5, 5, 3, 4, 5],
    stats: {
      putts: 35,
      fairways: "8/14",
      greens: "10/18",
      penalties: 2,
      birdies: 0,
      pars: 9,
      bogeys: 7,
      doubleBogeys: 2,
    },
    conditions: "Windy, 65°F, 18mph wind",
    playingPartners: ["Mike Thompson"],
    notes: "Tough day. Wind made it really difficult to score.",
    xpEarned: 70,
    trophyBalls: [],
  },
  {
    id: "rnd_005",
    date: "2024-10-29",
    course: "Fox Hollow Golf Course",
    score: 76,
    par: 72,
    differential: "+4",
    holes: [4, 4, 3, 3, 4, 5, 3, 4, 4, 4, 5, 3, 4, 4, 5, 3, 4, 4],
    stats: {
      putts: 31,
      fairways: "11/14",
      greens: "13/18",
      penalties: 0,
      birdies: 4,
      pars: 10,
      bogeys: 4,
      doubleBogeys: 0,
    },
    conditions: "Perfect, 70°F, 3mph wind",
    playingPartners: ["Dave Wilson", "Sarah Chen"],
    notes: "One of my best rounds! Everything was clicking.",
    xpEarned: 95,
    trophyBalls: [],
  },
  {
    id: "rnd_006",
    date: "2024-10-25",
    course: "Black Desert Resort",
    score: 80,
    par: 72,
    differential: "+8",
    holes: [4, 5, 4, 4, 4, 5, 3, 5, 4, 4, 5, 3, 4, 5, 5, 3, 4, 5],
    stats: {
      putts: 33,
      fairways: "9/14",
      greens: "11/18",
      penalties: 1,
      birdies: 2,
      pars: 10,
      bogeys: 5,
      doubleBogeys: 1,
    },
    conditions: "Sunny, 73°F, 10mph wind",
    playingPartners: ["Tom Reynolds"],
    notes: "Solid round at a tough course. Happy with how I played.",
    xpEarned: 80,
    trophyBalls: [],
  },
  {
    id: "rnd_007",
    date: "2024-10-21",
    course: "Entrada at Snow Canyon",
    score: 79,
    par: 72,
    differential: "+7",
    holes: [4, 5, 3, 4, 4, 5, 4, 4, 4, 4, 5, 3, 4, 4, 5, 3, 4, 5],
    stats: {
      putts: 32,
      fairways: "10/14",
      greens: "11/18",
      penalties: 1,
      birdies: 2,
      pars: 11,
      bogeys: 4,
      doubleBogeys: 1,
    },
    conditions: "Clear, 68°F, 6mph wind",
    playingPartners: ["John Martinez"],
    notes: "First time at Entrada. Beautiful course, will be back!",
    xpEarned: 85,
    trophyBalls: [],
  },
  {
    id: "rnd_008",
    date: "2024-10-17",
    course: "Sand Hollow Resort",
    score: 74,
    par: 72,
    differential: "+2",
    holes: [4, 4, 3, 4, 3, 5, 3, 4, 4, 4, 5, 3, 4, 4, 5, 3, 4, 4],
    stats: {
      putts: 28,
      fairways: "12/14",
      greens: "14/18",
      penalties: 0,
      birdies: 4,
      pars: 12,
      bogeys: 2,
      doubleBogeys: 0,
    },
    conditions: "Perfect, 72°F, calm",
    playingPartners: ["Mike Thompson", "Dave Wilson", "Sarah Chen"],
    notes: "BEST ROUND EVER! Everything clicked. This is my new benchmark.",
    xpEarned: 120,
    trophyBalls: ["personal-best"],
  },
  {
    id: "rnd_009",
    date: "2024-10-13",
    course: "Fox Hollow Golf Course",
    score: 80,
    par: 72,
    differential: "+8",
    holes: [4, 5, 3, 4, 4, 5, 4, 4, 5, 4, 5, 3, 4, 4, 5, 3, 4, 5],
    stats: {
      putts: 34,
      fairways: "9/14",
      greens: "10/18",
      penalties: 2,
      birdies: 1,
      pars: 10,
      bogeys: 6,
      doubleBogeys: 1,
    },
    conditions: "Overcast, 62°F, 12mph wind",
    playingPartners: ["Tom Reynolds"],
    notes: "Struggled with the putter today. Need to practice more.",
    xpEarned: 75,
    trophyBalls: [],
  },
  {
    id: "rnd_010",
    date: "2024-10-09",
    course: "SunBrook Golf Club",
    score: 78,
    par: 72,
    differential: "+6",
    holes: [4, 4, 3, 4, 4, 5, 3, 4, 4, 4, 5, 3, 4, 4, 5, 4, 4, 4],
    stats: {
      putts: 31,
      fairways: "10/14",
      greens: "12/18",
      penalties: 1,
      birdies: 3,
      pars: 10,
      bogeys: 4,
      doubleBogeys: 1,
    },
    conditions: "Sunny, 75°F, 7mph wind",
    playingPartners: ["Dave Wilson"],
    notes: "Good value course. Played well, especially on the back nine.",
    xpEarned: 80,
    trophyBalls: [],
  },
];

export async function getRounds(): Promise<Round[]> {
  await new Promise((resolve) => setTimeout(resolve, 100));
  return jasonRecentRounds;
}

export async function getRoundById(id: string): Promise<Round | null> {
  await new Promise((resolve) => setTimeout(resolve, 100));
  return jasonRecentRounds.find((round) => round.id === id) || null;
}

export async function addRound(round: Omit<Round, "id">): Promise<Round> {
  await new Promise((resolve) => setTimeout(resolve, 100));
  const newRound: Round = {
    ...round,
    id: `rnd_${Date.now()}`,
  };
  jasonRecentRounds.unshift(newRound);
  return newRound;
}

export async function getRecentRounds(limit: number = 5): Promise<Round[]> {
  await new Promise((resolve) => setTimeout(resolve, 100));
  return jasonRecentRounds.slice(0, limit);
}

export async function getRoundsByCourse(courseName: string): Promise<Round[]> {
  await new Promise((resolve) => setTimeout(resolve, 100));
  return jasonRecentRounds.filter((round) => round.course === courseName);
}
